[[headers]]
  for = "/*.unity3d"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/AssetBundles/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/octet-stream"